add project files
AbbyNyakara/where_in_the_world pull request #1
Opened 2022-08-11 13:21 UTC by AbbyNyakara

Create the where is the world project that displays the countries in the world and a few details like the Name, flag, capital etc

2022-08-11 16:23 UTC, EricMbouwe requested changes
Hi @AbbyNyakara, 

Good job so far! 🔥🔥🔥
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

# Suggested changes ♻
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-11 16:23 UTC, EricMbouwe commented on src/features/CountriesSlice.js
> +});
- [ ] Let's add some unit tests for functions in Redux code. You can perform a mocking data fetching

2022-08-11 16:23 UTC, EricMbouwe commented on src/components/Countries/Countries.scss
> +}
- [OPTIONAL] Since you are using scss, you can benefit from its power by using nesting instead of repeating yourself for the same selector.

eg:
```scss
.details {
  h2 {
    padding-bottom: 10px;
    font-size: 20px;
    font-weight: variables.$font-bolder;
  }
  h3 {
    padding-bottom: 5px;
    font-size: 16px;
    font-weight: variables.$font-bold;
  }
  h3 > span {
    color: variables.$clr-light-mode-input;
  }
}
```

2022-08-12 06:09 UTC, AbbyNyakara commented on src/features/CountriesSlice.js
> +});
Added tests for this section

2022-08-12 06:15 UTC, AbbyNyakara commented on src/components/Countries/Countries.scss
> +}
Great suggestion. Thanks

2022-08-12 06:22 UTC, AbbyNyakara commented
@EricMbouwe , please review. The changes are implemented

2022-08-12 06:28 UTC, EricMbouwe commented on src/features/CountriesSlice.js
> +});
Hello @AbbyNyakara, please be patient. Your PR has been claimed y another code reviewer😉

2022-08-12 06:29 UTC, EricMbouwe commented
Hello @AbbyNyakara, please be patient. Your PR has been claimed y another code reviewer😉

2022-08-12 06:52 UTC, AbbyNyakara commented
@EricMbouwe , thats weird, coz i did not request through the dashboard. Lemme just send it through the dashboard then.

2022-08-12 07:01 UTC, EricMbouwe commented
Oh I see. You need to request another Review through the dashboard.

2022-08-12 07:28 UTC, rotimiazeez approved these changes
# Hi @AbbyNyakara 👍🏽, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 10:08 UTC, merged